project_id = "mealmate"

[auth]
enable_anonymous_sign_ins = true
site_url = "mealmate://auth/callback"
additional_redirect_urls = ["mealmate://**", "exp://192.168.68.54:4174/--/auth/callback"]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = false
max_frequency = "1m"
otp_length = 8

[auth.external.apple]
enabled = true
client_id = "nl.mealmate.app,host.exp.Exponent"
secret = ""

[functions.parse-recipe]
verify_jwt = true

[functions.invite-family-member]
verify_jwt = false
